import { buildZipArchive } from "@/lib/thread-export"
import { BlobWriter, TextReader, ZipWriter } from "@zip.js/zip.js"

export interface AccountExportProfile {
    id: string
    name?: string | null
    email?: string | null
    emailVerified?: boolean
    createdAt?: Date | string | number
}

export interface AccountExportFile {
    name: string
    content: string
}

export interface AccountExportStoredFile {
    key: string
    url: string
    contentType?: string
    size?: number
    lastModified?: string | number
}

const REDACTED = "[REDACTED]"

const isSecretField = (key: string, parentKey?: string) =>
    key === "encryptedKey" ||
    key === "apiKey" ||
    key === "token" ||
    key === "secret" ||
    (parentKey === "headers" && key === "value")

const redactSecrets = (value: unknown, parentKey?: string): unknown => {
    if (Array.isArray(value)) {
        return value.map((item) => redactSecrets(item, parentKey))
    }

    if (!value || typeof value !== "object") return value

    return Object.fromEntries(
        Object.entries(value).map(([key, item]) => [
            key,
            isSecretField(key, parentKey) ? REDACTED : redactSecrets(item, key)
        ])
    )
}

export const sanitizeAccountExportSettings = (settings: unknown) => redactSecrets(settings)

export const buildAccountExportArchiveName = (exportedAt: number) => {
    const date = new Date(exportedAt).toISOString().slice(0, 10)
    return `${date}--silkchat-account-export.zip`
}

const buildAccountExportFiles = ({
    exportedAt,
    profile,
    settings,
    personas,
    projects,
    memories,
    storedFiles,
    threadFiles,
    threadCount
}: {
    exportedAt: number
    profile: AccountExportProfile
    settings: unknown
    personas: unknown[]
    projects: unknown[]
    memories: unknown[]
    storedFiles: AccountExportStoredFile[]
    threadFiles: AccountExportFile[]
    threadCount: number
}) => {
    const publicStoredFiles = storedFiles.map(({ key, url, contentType, size, lastModified }) => ({
        key,
        url,
        contentType,
        size,
        lastModified
    }))
    const manifest = {
        format: "silkchat-account-export",
        version: 1,
        exportedAt: new Date(exportedAt).toISOString(),
        contents: {
            profile: "account/profile.json",
            settings: "account/settings.json",
            personas: "account/personas.json",
            projects: "account/projects.json",
            memories: "memory/memories.json",
            memoryCount: memories.length,
            storedFiles: "files/index.json",
            storedFileCount: publicStoredFiles.length,
            conversationsDirectory: "conversations/",
            threadCount,
            exportedConversationCount: threadFiles.length
        },
        security: {
            redactedValues: ["AI provider credentials", "custom provider credentials"]
        }
    }

    const json = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`
    return {
        files: [
            { name: "manifest.json", content: json(manifest) },
            { name: "account/profile.json", content: json(profile) },
            {
                name: "account/settings.json",
                content: json(sanitizeAccountExportSettings(settings))
            },
            { name: "account/personas.json", content: json(personas) },
            { name: "account/projects.json", content: json(projects) },
            { name: "memory/memories.json", content: json(memories) },
            {
                name: "files/index.json",
                content: json({
                    description:
                        "Public links and metadata for files uploaded to or generated by Silkchat.",
                    files: publicStoredFiles
                })
            },
            {
                name: "files/README.txt",
                content:
                    "This directory contains an index of user-owned attachments, generated assets, code artifacts, persona files, and reference files stored by Silkchat.\n\nThe files remain in R2 and are represented by public links instead of being duplicated into this archive. Links stop working if the corresponding stored file is deleted.\n"
            },
            ...threadFiles.map((file) => ({
                name: `conversations/${file.name}`,
                content: file.content
            }))
        ],
        manifest
    }
}

export const buildAccountExportArchive = (
    options: Parameters<typeof buildAccountExportFiles>[0]
) => {
    const { files, manifest } = buildAccountExportFiles(options)

    return {
        blob: buildZipArchive(files),
        fileName: buildAccountExportArchiveName(options.exportedAt),
        manifest
    }
}

export const buildEncryptedAccountExportArchive = async ({
    password,
    ...options
}: Parameters<typeof buildAccountExportFiles>[0] & { password: string }) => {
    if (!password.trim()) throw new Error("Account export password is required")
    const { files, manifest } = buildAccountExportFiles(options)
    const writer = new ZipWriter(new BlobWriter("application/zip"), {
        password,
        encryptionStrength: 3,
        level: 6,
        useWebWorkers: false
    })
    for (const file of files) {
        await writer.add(file.name, new TextReader(file.content))
    }
    return {
        blob: await writer.close(),
        fileName: buildAccountExportArchiveName(options.exportedAt),
        manifest
    }
}
