/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/fal-r2-ingest/wrangler.jsonc --include-runtime=false workers/fal-r2-ingest/worker-configuration.d.ts` (hash: 8883527b6a5ec8c22bb76d93d48e9f1f)
interface __BaseEnv_Env {
    DESTINATION_BUCKET: R2Bucket
    ALLOWED_SOURCE_HOSTS: ".fal.media"
    MAX_ASSET_BYTES: "104857600"
    UPSTREAM_TIMEOUT_MS: "120000"
}
declare namespace Cloudflare {
    interface GlobalProps {
        mainModule: typeof import("./src/index")
    }
    interface StagingEnv {
        DESTINATION_BUCKET: R2Bucket
        ALLOWED_SOURCE_HOSTS: ".fal.media"
        MAX_ASSET_BYTES: "104857600"
        UPSTREAM_TIMEOUT_MS: "120000"
    }
    interface ProductionEnv {
        DESTINATION_BUCKET: R2Bucket
        ALLOWED_SOURCE_HOSTS: ".fal.media"
        MAX_ASSET_BYTES: "104857600"
        UPSTREAM_TIMEOUT_MS: "120000"
    }
    interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
    [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string
}
declare namespace NodeJS {
    interface ProcessEnv
        extends StringifyValues<
            Pick<Cloudflare.Env, "ALLOWED_SOURCE_HOSTS" | "MAX_ASSET_BYTES" | "UPSTREAM_TIMEOUT_MS">
        > {}
}
