import dedent from "ts-dedent"
import type { AppSkillDefinition } from "./types"

export const imageGenerationSkill: AppSkillDefinition = {
    id: "image_generation",
    label: "SilkScreen",
    summary: "Prepare image generation or edits using available image models and references.",
    toolNames: ["prepareImageGeneration"],
    buildInstructions: ({ imageGenerationDefaults, availableImageSelectionSummary }) => {
        const imageDefaultsSummary = `resolution ${imageGenerationDefaults?.resolution ?? "1K"}, variants ${imageGenerationDefaults?.variants ?? 1}`

        return dedent`
## SilkScreen Image Preparation Tool
You have an internal SilkScreen tool named \`prepareImageGeneration\`.
- Use it when the user asks to create, generate, draw, render, produce, or edit an image.
- Provide a short, human-friendly \`title\` (3-6 words) as the card heading.
- Choose only from the tool's valid enum inputs. Do not invent model ids, aspect ratios, resolutions, variant counts, or reference ids.
- Explicit nudity is best generated by Seedream 5 Lite. If the user requests it, you may use Seedream 5 Lite for non-explicit content as well.
- Most other mildly NSFW content can be generated by other models except Google or Flux.
- GPT Image 2.5 Flare is the general-purpose choice for fast generation. Use GPT Image 2.5 Sunburst when precise edits and preserving fine details matter most.

**Behaviour**
The tool only prepares a pending confirmation card — it doesn't generate pixels, submit a job, or spend credits. A successful call is a valid final assistant action: stop the turn with no extra text once it returns; the user confirms on the card before anything is generated. Don't imply the image exists until a later turn shows a completed result.

**Resolution & variants**
Leave both unset by default to use the user's saved defaults (${imageDefaultsSummary}). You are permitted to override when the request implies a different count or fidelity — raise variants for multiple options/variations, raise resolution for print-quality or high-fidelity requests, lower it for drafts/sketches/demos/non-concrete ideas. Infer intent from context; you don't need explicit numbers stated. If ambiguous, stick with the defaults. examples:
- "generate a logo" → leave unset
- "a few different logo options" → set variants
- "quick draft of a logo" → lower resolution
- "print-ready poster design" → raise resolution

The count belongs in \`variants\`, never in the prompt words. Each variant is an independent generation of the *same* prompt, so the prompt must describe ONE image in the singular — strip "a few", "several", "options", "variations", grids, and numbers out of it even when the user phrases the request that way, or each generation packs multiple designs into a single image.
- User: "a few types/generations/drafts/variants/designs etc of ACME logo" → \`variants\` 4, prompt: "A logo for ACME — [description]" (one design, singular)
- Not: \`variants\` 4, prompt: "Create a few variations…" (the plural leaks into the prompt and each of the 4 generations renders several logos at once)

Call \`prepareImageGeneration\` exactly once per distinct image. Never call it repeatedly to produce copies of the same card — that is what the \`variants\` field is for. Two calls are only correct when the images are genuinely different (e.g. a logo and a banner).

**Editing existing images**
You MUST pass the reference id whenever the request edits, transforms, restyles, or builds on an existing image (an attachment, a provided image, or one you generated earlier) — this is what makes SilkScreen edit that image rather than generating a new one. If the user clearly means an existing image but no reference id is available, ask them to attach or select it first. If multiple variants exist and the user says "that image" or "one of those" without specifying which, ask rather than guess.
it is highly recommended to start over a prompt instead of passing a reference if a generated image is flawed or the user is unsatisfied with it. References are best used for user supplied content.
Available SilkScreen image selections:
${availableImageSelectionSummary ?? "- None"}`
    }
}
