"use node"

import { MAX_FILE_SIZE } from "@/lib/file_constants"
import { internal } from "../_generated/api"
import type { ActionCtx } from "../_generated/server"
import { r2 } from "../attachments"
import {
    FileSizeLimitError,
    PdfContentError,
    assertPdfPageCount,
    inspectPdfBytes,
    readResponseBytesWithinLimit
} from "./pdf_validation_node"

// Keys are generated by the server and direct uploads use If-None-Match: *.
// Metadata identity invalidates cached results if an object is replaced and resynced.
export const validateStoredPdf = async (ctx: ActionCtx, storageKey: string, fileName: string) => {
    if (!storageKey.startsWith("attachments/")) {
        throw new Error("External PDFs cannot be used in chat. Upload the PDF again")
    }
    const metadata = await r2.getMetadata(ctx, storageKey)
    if (metadata?.uploadStatus !== "ready" || !metadata.lastModified) {
        throw new Error(`${fileName}: PDF is unavailable. Upload it again`)
    }
    if (typeof metadata.size !== "number") {
        throw new Error(`${fileName}: PDF size is unavailable. Upload it again`)
    }
    const objectVersion = JSON.stringify([
        metadata.bucket,
        metadata.lastModified,
        metadata.size,
        metadata.sha256 ?? null
    ])
    const cached = await ctx.runQuery(internal.pdf_validations.get, { storageKey })
    if (cached?.objectVersion === objectVersion) {
        if (cached.error) throw new Error(cached.error)
        if (metadata.size <= MAX_FILE_SIZE && typeof cached.pageCount === "number") {
            assertPdfPageCount(cached.pageCount, fileName)
            return cached.pageCount
        }
    }

    let pageCount: number
    try {
        if (metadata.size > MAX_FILE_SIZE) {
            throw new FileSizeLimitError(`${fileName}: PDF exceeds the file size limit`)
        }
        const response = await fetch(await r2.getUrl(storageKey), {
            signal: AbortSignal.timeout(30_000)
        })
        if (!response.ok) throw new Error(`${fileName}: Failed to download PDF for validation`)
        const bytes = await readResponseBytesWithinLimit(response, MAX_FILE_SIZE)
        if (bytes.byteLength !== metadata.size)
            throw new Error(`${fileName}: PDF changed during validation`)
        pageCount = (await inspectPdfBytes(bytes, fileName)).pageCount
    } catch (error) {
        if (error instanceof PdfContentError || error instanceof FileSizeLimitError) {
            await ctx.runMutation(internal.pdf_validations.save, {
                storageKey,
                objectVersion,
                error: error.message
            })
        }
        throw error
    }
    await ctx.runMutation(internal.pdf_validations.save, { storageKey, objectVersion, pageCount })
    assertPdfPageCount(pageCount, fileName)
    return pageCount
}
