/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TosRouteImport } from './routes/tos'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MeRouteImport } from './routes/me'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as AuthorRouteImport } from './routes/author'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsUsageRouteImport } from './routes/settings/usage'
import { Route as SettingsProvidersRouteImport } from './routes/settings/providers'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsPersonasRouteImport } from './routes/settings/personas'
import { Route as SettingsModelsRouteImport } from './routes/settings/models'
import { Route as SettingsFilesRouteImport } from './routes/settings/files'
import { Route as SettingsCustomizationRouteImport } from './routes/settings/customization'
import { Route as SettingsBillingRouteImport } from './routes/settings/billing'
import { Route as SettingsBehaviorRouteImport } from './routes/settings/behavior'
import { Route as SettingsAttachmentsRouteImport } from './routes/settings/attachments'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsAiSetupRouteImport } from './routes/settings/ai-setup'
import { Route as SettingsAiOptionsRouteImport } from './routes/settings/ai-options'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as ApiModelBenchmarksRouteImport } from './routes/api/model-benchmarks'
import { Route as ApiCreditSummaryRouteImport } from './routes/api/credit-summary'
import { Route as ChatLibraryRouteImport } from './routes/_chat.library'
import { Route as ApiPhrSplatRouteImport } from './routes/api/phr/$'
import { Route as ApiDevCreditPlanRouteImport } from './routes/api/dev/credit-plan'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ChatThreadThreadIdRouteImport } from './routes/_chat.thread.$threadId'
import { Route as ChatFolderFolderIdThreadThreadIdRouteImport } from './routes/_chat.folder.$folderId.thread.$threadId'

const AboutLazyRouteImport = createFileRoute('/about')()
const SettingsRouteLazyRouteImport = createFileRoute('/settings')()
const AuthPathnameLazyRouteImport = createFileRoute('/auth/$pathname')()
const ChatSSharedThreadIdLazyRouteImport = createFileRoute(
  '/_chat/s/$sharedThreadId',
)()
const ChatFolderFolderIdLazyRouteImport = createFileRoute(
  '/_chat/folder/$folderId',
)()

const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const SettingsRouteLazyRoute = SettingsRouteLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/settings/route.lazy').then((d) => d.Route),
)
const TosRoute = TosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/terms-of-service.lazy').then((d) => d.Route),
)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/privacy-policy.lazy').then((d) => d.Route),
)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorRoute = AuthorRouteImport.update({
  id: '/author',
  path: '/author',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const AuthPathnameLazyRoute = AuthPathnameLazyRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/auth/$pathname.lazy').then((d) => d.Route),
)
const SettingsUsageRoute = SettingsUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any)
const SettingsPersonasRoute = SettingsPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any)
const SettingsModelsRoute = SettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any)
const SettingsFilesRoute = SettingsFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any)
const SettingsCustomizationRoute = SettingsCustomizationRouteImport.update({
  id: '/customization',
  path: '/customization',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any)
const SettingsBehaviorRoute = SettingsBehaviorRouteImport.update({
  id: '/behavior',
  path: '/behavior',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any)
const SettingsAttachmentsRoute = SettingsAttachmentsRouteImport.update({
  id: '/attachments',
  path: '/attachments',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any)
const SettingsAiSetupRoute = SettingsAiSetupRouteImport.update({
  id: '/ai-setup',
  path: '/ai-setup',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any)
const SettingsAiOptionsRoute = SettingsAiOptionsRouteImport.update({
  id: '/ai-options',
  path: '/ai-options',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any)
const ApiModelBenchmarksRoute = ApiModelBenchmarksRouteImport.update({
  id: '/api/model-benchmarks',
  path: '/api/model-benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreditSummaryRoute = ApiCreditSummaryRouteImport.update({
  id: '/api/credit-summary',
  path: '/api/credit-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatLibraryRoute = ChatLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSSharedThreadIdLazyRoute = ChatSSharedThreadIdLazyRouteImport.update({
  id: '/s/$sharedThreadId',
  path: '/s/$sharedThreadId',
  getParentRoute: () => ChatRoute,
} as any).lazy(() =>
  import('./routes/_chat.s.$sharedThreadId.lazy').then((d) => d.Route),
)
const ChatFolderFolderIdLazyRoute = ChatFolderFolderIdLazyRouteImport.update({
  id: '/folder/$folderId',
  path: '/folder/$folderId',
  getParentRoute: () => ChatRoute,
} as any).lazy(() =>
  import('./routes/_chat.folder.$folderId.lazy').then((d) => d.Route),
)
const ApiPhrSplatRoute = ApiPhrSplatRouteImport.update({
  id: '/api/phr/$',
  path: '/api/phr/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevCreditPlanRoute = ApiDevCreditPlanRouteImport.update({
  id: '/api/dev/credit-plan',
  path: '/api/dev/credit-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadThreadIdRoute = ChatThreadThreadIdRouteImport.update({
  id: '/thread/$threadId',
  path: '/thread/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatFolderFolderIdThreadThreadIdRoute =
  ChatFolderFolderIdThreadThreadIdRouteImport.update({
    id: '/thread/$threadId',
    path: '/thread/$threadId',
    getParentRoute: () => ChatFolderFolderIdLazyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/author': typeof AuthorRoute
  '/legal': typeof LegalRoute
  '/me': typeof MeRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tos': typeof TosRoute
  '/settings': typeof SettingsRouteLazyRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/library': typeof ChatLibraryRoute
  '/api/credit-summary': typeof ApiCreditSummaryRoute
  '/api/model-benchmarks': typeof ApiModelBenchmarksRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/ai-options': typeof SettingsAiOptionsRoute
  '/settings/ai-setup': typeof SettingsAiSetupRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/attachments': typeof SettingsAttachmentsRoute
  '/settings/behavior': typeof SettingsBehaviorRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/customization': typeof SettingsCustomizationRoute
  '/settings/files': typeof SettingsFilesRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/personas': typeof SettingsPersonasRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/auth/$pathname': typeof AuthPathnameLazyRoute
  '/thread/$threadId': typeof ChatThreadThreadIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dev/credit-plan': typeof ApiDevCreditPlanRoute
  '/api/phr/$': typeof ApiPhrSplatRoute
  '/folder/$folderId': typeof ChatFolderFolderIdLazyRouteWithChildren
  '/s/$sharedThreadId': typeof ChatSSharedThreadIdLazyRoute
  '/folder/$folderId/thread/$threadId': typeof ChatFolderFolderIdThreadThreadIdRoute
}
export interface FileRoutesByTo {
  '/author': typeof AuthorRoute
  '/legal': typeof LegalRoute
  '/me': typeof MeRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tos': typeof TosRoute
  '/settings': typeof SettingsRouteLazyRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/library': typeof ChatLibraryRoute
  '/api/credit-summary': typeof ApiCreditSummaryRoute
  '/api/model-benchmarks': typeof ApiModelBenchmarksRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/ai-options': typeof SettingsAiOptionsRoute
  '/settings/ai-setup': typeof SettingsAiSetupRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/attachments': typeof SettingsAttachmentsRoute
  '/settings/behavior': typeof SettingsBehaviorRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/customization': typeof SettingsCustomizationRoute
  '/settings/files': typeof SettingsFilesRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/personas': typeof SettingsPersonasRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/auth/$pathname': typeof AuthPathnameLazyRoute
  '/': typeof ChatIndexRoute
  '/thread/$threadId': typeof ChatThreadThreadIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dev/credit-plan': typeof ApiDevCreditPlanRoute
  '/api/phr/$': typeof ApiPhrSplatRoute
  '/folder/$folderId': typeof ChatFolderFolderIdLazyRouteWithChildren
  '/s/$sharedThreadId': typeof ChatSSharedThreadIdLazyRoute
  '/folder/$folderId/thread/$threadId': typeof ChatFolderFolderIdThreadThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/author': typeof AuthorRoute
  '/legal': typeof LegalRoute
  '/me': typeof MeRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tos': typeof TosRoute
  '/settings': typeof SettingsRouteLazyRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/_chat/library': typeof ChatLibraryRoute
  '/api/credit-summary': typeof ApiCreditSummaryRoute
  '/api/model-benchmarks': typeof ApiModelBenchmarksRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/ai-options': typeof SettingsAiOptionsRoute
  '/settings/ai-setup': typeof SettingsAiSetupRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/attachments': typeof SettingsAttachmentsRoute
  '/settings/behavior': typeof SettingsBehaviorRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/customization': typeof SettingsCustomizationRoute
  '/settings/files': typeof SettingsFilesRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/personas': typeof SettingsPersonasRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/auth/$pathname': typeof AuthPathnameLazyRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/thread/$threadId': typeof ChatThreadThreadIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dev/credit-plan': typeof ApiDevCreditPlanRoute
  '/api/phr/$': typeof ApiPhrSplatRoute
  '/_chat/folder/$folderId': typeof ChatFolderFolderIdLazyRouteWithChildren
  '/_chat/s/$sharedThreadId': typeof ChatSSharedThreadIdLazyRoute
  '/_chat/folder/$folderId/thread/$threadId': typeof ChatFolderFolderIdThreadThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/author'
    | '/legal'
    | '/me'
    | '/privacy'
    | '/privacy-policy'
    | '/terms'
    | '/terms-of-service'
    | '/tos'
    | '/settings'
    | '/about'
    | '/library'
    | '/api/credit-summary'
    | '/api/model-benchmarks'
    | '/settings/account'
    | '/settings/ai-options'
    | '/settings/ai-setup'
    | '/settings/appearance'
    | '/settings/attachments'
    | '/settings/behavior'
    | '/settings/billing'
    | '/settings/customization'
    | '/settings/files'
    | '/settings/models'
    | '/settings/personas'
    | '/settings/profile'
    | '/settings/providers'
    | '/settings/usage'
    | '/auth/$pathname'
    | '/thread/$threadId'
    | '/api/auth/$'
    | '/api/dev/credit-plan'
    | '/api/phr/$'
    | '/folder/$folderId'
    | '/s/$sharedThreadId'
    | '/folder/$folderId/thread/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/author'
    | '/legal'
    | '/me'
    | '/privacy'
    | '/privacy-policy'
    | '/terms'
    | '/terms-of-service'
    | '/tos'
    | '/settings'
    | '/about'
    | '/library'
    | '/api/credit-summary'
    | '/api/model-benchmarks'
    | '/settings/account'
    | '/settings/ai-options'
    | '/settings/ai-setup'
    | '/settings/appearance'
    | '/settings/attachments'
    | '/settings/behavior'
    | '/settings/billing'
    | '/settings/customization'
    | '/settings/files'
    | '/settings/models'
    | '/settings/personas'
    | '/settings/profile'
    | '/settings/providers'
    | '/settings/usage'
    | '/auth/$pathname'
    | '/'
    | '/thread/$threadId'
    | '/api/auth/$'
    | '/api/dev/credit-plan'
    | '/api/phr/$'
    | '/folder/$folderId'
    | '/s/$sharedThreadId'
    | '/folder/$folderId/thread/$threadId'
  id:
    | '__root__'
    | '/_chat'
    | '/author'
    | '/legal'
    | '/me'
    | '/privacy'
    | '/privacy-policy'
    | '/terms'
    | '/terms-of-service'
    | '/tos'
    | '/settings'
    | '/about'
    | '/_chat/library'
    | '/api/credit-summary'
    | '/api/model-benchmarks'
    | '/settings/account'
    | '/settings/ai-options'
    | '/settings/ai-setup'
    | '/settings/appearance'
    | '/settings/attachments'
    | '/settings/behavior'
    | '/settings/billing'
    | '/settings/customization'
    | '/settings/files'
    | '/settings/models'
    | '/settings/personas'
    | '/settings/profile'
    | '/settings/providers'
    | '/settings/usage'
    | '/auth/$pathname'
    | '/_chat/'
    | '/_chat/thread/$threadId'
    | '/api/auth/$'
    | '/api/dev/credit-plan'
    | '/api/phr/$'
    | '/_chat/folder/$folderId'
    | '/_chat/s/$sharedThreadId'
    | '/_chat/folder/$folderId/thread/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  AuthorRoute: typeof AuthorRoute
  LegalRoute: typeof LegalRoute
  MeRoute: typeof MeRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsRoute: typeof TermsRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  TosRoute: typeof TosRoute
  SettingsRouteLazyRoute: typeof SettingsRouteLazyRouteWithChildren
  AboutLazyRoute: typeof AboutLazyRoute
  ApiCreditSummaryRoute: typeof ApiCreditSummaryRoute
  ApiModelBenchmarksRoute: typeof ApiModelBenchmarksRoute
  AuthPathnameLazyRoute: typeof AuthPathnameLazyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDevCreditPlanRoute: typeof ApiDevCreditPlanRoute
  ApiPhrSplatRoute: typeof ApiPhrSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author': {
      id: '/author'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/usage': {
      id: '/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof SettingsUsageRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/personas': {
      id: '/settings/personas'
      path: '/personas'
      fullPath: '/settings/personas'
      preLoaderRoute: typeof SettingsPersonasRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/models': {
      id: '/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof SettingsModelsRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/files': {
      id: '/settings/files'
      path: '/files'
      fullPath: '/settings/files'
      preLoaderRoute: typeof SettingsFilesRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/customization': {
      id: '/settings/customization'
      path: '/customization'
      fullPath: '/settings/customization'
      preLoaderRoute: typeof SettingsCustomizationRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/behavior': {
      id: '/settings/behavior'
      path: '/behavior'
      fullPath: '/settings/behavior'
      preLoaderRoute: typeof SettingsBehaviorRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/attachments': {
      id: '/settings/attachments'
      path: '/attachments'
      fullPath: '/settings/attachments'
      preLoaderRoute: typeof SettingsAttachmentsRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/ai-setup': {
      id: '/settings/ai-setup'
      path: '/ai-setup'
      fullPath: '/settings/ai-setup'
      preLoaderRoute: typeof SettingsAiSetupRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/ai-options': {
      id: '/settings/ai-options'
      path: '/ai-options'
      fullPath: '/settings/ai-options'
      preLoaderRoute: typeof SettingsAiOptionsRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/api/model-benchmarks': {
      id: '/api/model-benchmarks'
      path: '/api/model-benchmarks'
      fullPath: '/api/model-benchmarks'
      preLoaderRoute: typeof ApiModelBenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credit-summary': {
      id: '/api/credit-summary'
      path: '/api/credit-summary'
      fullPath: '/api/credit-summary'
      preLoaderRoute: typeof ApiCreditSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/library': {
      id: '/_chat/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof ChatLibraryRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/s/$sharedThreadId': {
      id: '/_chat/s/$sharedThreadId'
      path: '/s/$sharedThreadId'
      fullPath: '/s/$sharedThreadId'
      preLoaderRoute: typeof ChatSSharedThreadIdLazyRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/folder/$folderId': {
      id: '/_chat/folder/$folderId'
      path: '/folder/$folderId'
      fullPath: '/folder/$folderId'
      preLoaderRoute: typeof ChatFolderFolderIdLazyRouteImport
      parentRoute: typeof ChatRoute
    }
    '/api/phr/$': {
      id: '/api/phr/$'
      path: '/api/phr/$'
      fullPath: '/api/phr/$'
      preLoaderRoute: typeof ApiPhrSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/credit-plan': {
      id: '/api/dev/credit-plan'
      path: '/api/dev/credit-plan'
      fullPath: '/api/dev/credit-plan'
      preLoaderRoute: typeof ApiDevCreditPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/thread/$threadId': {
      id: '/_chat/thread/$threadId'
      path: '/thread/$threadId'
      fullPath: '/thread/$threadId'
      preLoaderRoute: typeof ChatThreadThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/folder/$folderId/thread/$threadId': {
      id: '/_chat/folder/$folderId/thread/$threadId'
      path: '/thread/$threadId'
      fullPath: '/folder/$folderId/thread/$threadId'
      preLoaderRoute: typeof ChatFolderFolderIdThreadThreadIdRouteImport
      parentRoute: typeof ChatFolderFolderIdLazyRoute
    }
  }
}

interface ChatFolderFolderIdLazyRouteChildren {
  ChatFolderFolderIdThreadThreadIdRoute: typeof ChatFolderFolderIdThreadThreadIdRoute
}

const ChatFolderFolderIdLazyRouteChildren: ChatFolderFolderIdLazyRouteChildren =
  {
    ChatFolderFolderIdThreadThreadIdRoute:
      ChatFolderFolderIdThreadThreadIdRoute,
  }

const ChatFolderFolderIdLazyRouteWithChildren =
  ChatFolderFolderIdLazyRoute._addFileChildren(
    ChatFolderFolderIdLazyRouteChildren,
  )

interface ChatRouteChildren {
  ChatLibraryRoute: typeof ChatLibraryRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ChatThreadThreadIdRoute: typeof ChatThreadThreadIdRoute
  ChatFolderFolderIdLazyRoute: typeof ChatFolderFolderIdLazyRouteWithChildren
  ChatSSharedThreadIdLazyRoute: typeof ChatSSharedThreadIdLazyRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatLibraryRoute: ChatLibraryRoute,
  ChatIndexRoute: ChatIndexRoute,
  ChatThreadThreadIdRoute: ChatThreadThreadIdRoute,
  ChatFolderFolderIdLazyRoute: ChatFolderFolderIdLazyRouteWithChildren,
  ChatSSharedThreadIdLazyRoute: ChatSSharedThreadIdLazyRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteLazyRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsAiOptionsRoute: typeof SettingsAiOptionsRoute
  SettingsAiSetupRoute: typeof SettingsAiSetupRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsAttachmentsRoute: typeof SettingsAttachmentsRoute
  SettingsBehaviorRoute: typeof SettingsBehaviorRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsCustomizationRoute: typeof SettingsCustomizationRoute
  SettingsFilesRoute: typeof SettingsFilesRoute
  SettingsModelsRoute: typeof SettingsModelsRoute
  SettingsPersonasRoute: typeof SettingsPersonasRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsUsageRoute: typeof SettingsUsageRoute
}

const SettingsRouteLazyRouteChildren: SettingsRouteLazyRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsAiOptionsRoute: SettingsAiOptionsRoute,
  SettingsAiSetupRoute: SettingsAiSetupRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsAttachmentsRoute: SettingsAttachmentsRoute,
  SettingsBehaviorRoute: SettingsBehaviorRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsCustomizationRoute: SettingsCustomizationRoute,
  SettingsFilesRoute: SettingsFilesRoute,
  SettingsModelsRoute: SettingsModelsRoute,
  SettingsPersonasRoute: SettingsPersonasRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsUsageRoute: SettingsUsageRoute,
}

const SettingsRouteLazyRouteWithChildren =
  SettingsRouteLazyRoute._addFileChildren(SettingsRouteLazyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  AuthorRoute: AuthorRoute,
  LegalRoute: LegalRoute,
  MeRoute: MeRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsRoute: TermsRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  TosRoute: TosRoute,
  SettingsRouteLazyRoute: SettingsRouteLazyRouteWithChildren,
  AboutLazyRoute: AboutLazyRoute,
  ApiCreditSummaryRoute: ApiCreditSummaryRoute,
  ApiModelBenchmarksRoute: ApiModelBenchmarksRoute,
  AuthPathnameLazyRoute: AuthPathnameLazyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDevCreditPlanRoute: ApiDevCreditPlanRoute,
  ApiPhrSplatRoute: ApiPhrSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
